# Generated by Django 5.2.10 on 2026-01-09 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Yurt Adı')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu')),
                ('dorm_type', models.CharField(choices=[('KIZ', 'Kız Yurdu'), ('ERKEK', 'Erkek Yurdu'), ('KARMA', 'Karma Yurt'), ('APART', 'Öğrenci Apartı')], default='KARMA', max_length=20, verbose_name='Yurt Tipi')),
                ('city', models.CharField(choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50, verbose_name='Şehir')),
                ('district', models.CharField(max_length=100, verbose_name='İlçe/Semt')),
                ('address', models.TextField(blank=True, verbose_name='Tam Adres')),
                ('price', models.IntegerField(help_text='Yıllık/Aylık', verbose_name='Fiyat')),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='dorm_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='dorm_covers/')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Ana Vitrin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yurt',
                'verbose_name_plural': 'Yurtlar',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Özellik Adı')),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name (e.g., Wifi, Coffee)', max_length=50)),
            ],
            options={
                'verbose_name': 'Özellik / İkon',
                'verbose_name_plural': 'Özellik Havuzu',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cover_image', models.ImageField(upload_to='news/covers/')),
                ('summary', models.TextField(blank=True, max_length=300, null=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Gundem', 'Gündem'), ('Sinav', 'Sınav'), ('Kariyer', 'Kariyer'), ('Yasam', 'Yaşam'), ('Teknoloji', 'Teknoloji'), ('Burslar', 'Burslar')], default='Yasam', max_length=50)),
                ('author', models.CharField(default='Kampüs Editör', max_length=100)),
                ('is_published', models.BooleanField(default=True)),
                ('is_breaking', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Haberler',
            },
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='scholarships/logos/')),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('city', models.CharField(blank=True, choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50, null=True)),
                ('education_level', models.CharField(choices=[('Lise', 'Lise'), ('Lisans', 'Lisans'), ('YuksekLisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], default='Lisans', max_length=50)),
                ('category', models.CharField(choices=[('Basari', 'Başarı'), ('Ihtiyac', 'İhtiyaç'), ('Spor', 'Spor'), ('Sanat', 'Sanat'), ('Kurumsal', 'Kurumsal'), ('KYK', 'KYK')], default='Basari', max_length=50)),
                ('application_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Burs Fırsatları',
            },
        ),
        migrations.CreateModel(
            name='DormitoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dorm_gallery/')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.dormitory')),
            ],
        ),
        migrations.AddField(
            model_name='dormitory',
            name='features',
            field=models.ManyToManyField(blank=True, to='api.feature'),
        ),
        migrations.CreateModel(
            name='StudentHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('city', models.CharField(choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('room_count', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('is_furnished', models.BooleanField(default=True)),
                ('square_meters', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='house_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, to='api.feature')),
            ],
            options={
                'verbose_name': 'Öğrenci Evi',
                'verbose_name_plural': 'Öğrenci Evleri',
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_gallery/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.studenthouse')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Üniversite Adı')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu')),
                ('city', models.CharField(choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50, verbose_name='Şehir')),
                ('uni_type', models.CharField(choices=[('DEVLET', 'Devlet'), ('VAKIF', 'Vakıf'), ('OZEL', 'Özel'), ('KIBRIS', 'Kıbrıs'), ('YABANCI', 'Yabancı')], default='DEVLET', max_length=20)),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Kuruluş Yılı')),
                ('rector', models.CharField(blank=True, max_length=100, verbose_name='Rektör')),
                ('student_count', models.IntegerField(default=0, verbose_name='Öğrenci Sayısı')),
                ('academician_count', models.IntegerField(default=0, verbose_name='Akademisyen Sayısı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('map_location', models.CharField(blank=True, max_length=500, verbose_name='Harita Embed Linki')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uni_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uni_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, to='api.feature', verbose_name='Kampüs İmkanları')),
            ],
            options={
                'verbose_name': 'Üniversite',
                'verbose_name_plural': 'Üniversiteler',
            },
        ),
        migrations.CreateModel(
            name='DormitoryDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_text', models.CharField(help_text='Örn: 5 dk Yürüme', max_length=100, verbose_name='Mesafe')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Vitrin/Partner')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dormitory')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university')),
            ],
            options={
                'verbose_name': 'Hizmet İlişkisi',
                'verbose_name_plural': 'Hizmet İlişkileri',
                'unique_together': {('university', 'dormitory')},
            },
        ),
        migrations.AddField(
            model_name='dormitory',
            name='universities',
            field=models.ManyToManyField(related_name='dormitories', through='api.DormitoryDistance', to='api.university'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20, unique=True, verbose_name='Program Kodu (YÖK ID)')),
                ('name', models.CharField(max_length=200, verbose_name='Bölüm Adı')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Fakülte')),
                ('language', models.CharField(default='Türkçe', max_length=50, verbose_name='Eğitim Dili')),
                ('duration', models.IntegerField(default=4, verbose_name='Süre (Yıl)')),
                ('score_type', models.CharField(choices=[('SAY', 'Sayısal'), ('EA', 'Eşit Ağırlık'), ('SOZ', 'Sözel'), ('DIL', 'Dil'), ('TYT', 'TYT')], default='SAY', max_length=10, verbose_name='Puan Türü')),
                ('education_type', models.CharField(default='Örgün Öğretim', max_length=50, verbose_name='Öğretim Türü')),
                ('quota', models.IntegerField(blank=True, null=True, verbose_name='Genel Kontenjan')),
                ('school_rank_quota', models.IntegerField(blank=True, null=True, verbose_name='Okul 1. Kontenjanı')),
                ('base_score', models.FloatField(blank=True, null=True, verbose_name='Taban Puan (2024)')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='Başarı Sıralaması (2024)')),
                ('special_conditions', models.TextField(blank=True, verbose_name='Özel Koşullar')),
                ('accreditation', models.CharField(blank=True, max_length=100, verbose_name='Akreditasyon')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='CampusVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mekan Adı')),
                ('venue_type', models.CharField(max_length=50, verbose_name='Tür')),
                ('image', models.ImageField(upload_to='venues/', verbose_name='Mekan Görseli')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('distance', models.CharField(max_length=50, verbose_name='Uzaklık')),
                ('is_sponsored', models.BooleanField(default=False)),
                ('discount_text', models.CharField(blank=True, max_length=100)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uni_gallery/')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.university')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteDormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.dormitory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dormitories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'dormitory')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteStudentHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_houses', to=settings.AUTH_USER_MODEL)),
                ('student_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.studenthouse')),
            ],
            options={
                'unique_together': {('user', 'student_house')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_universities', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.university')),
            ],
            options={
                'unique_together': {('user', 'university')},
            },
        ),
    ]
