# Generated by Django 5.2.10 on 2026-01-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AddField(
            model_name='news',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Instagram, Youtube vb. sitelerden alınan <iframe> veya <blockquote> kodunu buraya yapıştırın.', null=True, verbose_name='Sosyal Medya Embed Kodu'),
        ),
        migrations.AddField(
            model_name='news',
            name='show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Anasayfada Göster (Reels Vitrini)'),
        ),
    ]
