# Generated by Django 5.2.10 on 2026-01-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('SCHOLARSHIP', 'Burs Başvurusu'), ('INFO_REQUEST', 'Bilgi Talebi'), ('CAMPUS_TOUR', 'Kampüs Turu İsteği'), ('DORM_APPLY', 'Yurt Başvurusu')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.university')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.department')),
            ],
            options={
                'unique_together': {('department', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UniversityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('page_views', models.PositiveIntegerField(default=0)),
                ('search_appearances', models.PositiveIntegerField(default=0)),
                ('website_clicks', models.PositiveIntegerField(default=0)),
                ('phone_clicks', models.PositiveIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.university')),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'university'], name='api_univers_date_970577_idx')],
                'unique_together': {('university', 'date')},
            },
        ),
    ]
