# Generated by Django 5.2.10 on 2026-01-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_options_news_embed_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='embed_code',
        ),
        migrations.RemoveField(
            model_name='news',
            name='show_on_homepage',
        ),
        migrations.CreateModel(
            name='CampusReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Video Başlığı')),
                ('embed_code', models.TextField(help_text='Instagram/Youtube embed kodunu buraya yapıştırın.', verbose_name='Embed Kodu')),
                ('show_on_homepage', models.BooleanField(default=False, verbose_name='Anasayfa Vitrininde Göster')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme Tarihi')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='api.university', verbose_name='İlgili Üniversite')),
            ],
            options={
                'verbose_name': 'Kampüs Reels / Video',
                'verbose_name_plural': 'Kampüs Reels Videoları',
                'ordering': ['-created_at'],
            },
        ),
    ]
