# Generated by Django 5.2.10 on 2026-01-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_news_embed_code_remove_news_show_on_homepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('page_views', models.PositiveIntegerField(default=0, verbose_name='Sayfa Görüntülenme')),
                ('search_appearances', models.PositiveIntegerField(default=0, verbose_name='Aramada Görünme')),
                ('website_clicks', models.PositiveIntegerField(default=0, verbose_name='Website Tıklama')),
                ('phone_clicks', models.PositiveIntegerField(default=0, verbose_name='Telefon Tıklama')),
            ],
            options={
                'verbose_name': 'Günlük Trafik Analizi',
                'verbose_name_plural': 'Günlük Trafik Analizleri',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='campusreel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kampüs Reels', 'verbose_name_plural': 'Kampüs Reels Videoları'},
        ),
        migrations.AlterModelOptions(
            name='universitystats',
            options={'verbose_name': 'Üniversite Kalite Puanı (TÜMA)', 'verbose_name_plural': 'Üniversite Kalite Puanları'},
        ),
        migrations.RemoveIndex(
            model_name='universitystats',
            name='api_univers_date_970577_idx',
        ),
        migrations.AlterUniqueTogether(
            name='universitystats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='academic_score',
            field=models.IntegerField(default=50, verbose_name='Akademik Puan'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='campus_score',
            field=models.IntegerField(default=50, verbose_name='Kampüs Puanı'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='career_score',
            field=models.IntegerField(default=50, verbose_name='Kariyer Desteği Puanı'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='city_score',
            field=models.IntegerField(default=70, verbose_name='Şehir Cazibesi'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='social_score',
            field=models.IntegerField(default=50, verbose_name='Sosyal Yaşam Puanı'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='source',
            field=models.CharField(default='TÜMA 2025', max_length=100, verbose_name='Veri Kaynağı'),
        ),
        migrations.AddField(
            model_name='universitystats',
            name='tech_score',
            field=models.IntegerField(default=50, verbose_name='Teknoloji/İmkan Puanı'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='university',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AddField(
            model_name='universityanalytics',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.RemoveField(
            model_name='universitystats',
            name='date',
        ),
        migrations.RemoveField(
            model_name='universitystats',
            name='page_views',
        ),
        migrations.RemoveField(
            model_name='universitystats',
            name='phone_clicks',
        ),
        migrations.RemoveField(
            model_name='universitystats',
            name='search_appearances',
        ),
        migrations.RemoveField(
            model_name='universitystats',
            name='website_clicks',
        ),
        migrations.AddIndex(
            model_name='universityanalytics',
            index=models.Index(fields=['date', 'university'], name='api_univers_date_07d0cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='universityanalytics',
            unique_together={('university', 'date')},
        ),
    ]
