# Generated by Django 5.2.10 on 2026-01-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_university_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='doc_count',
            field=models.IntegerField(default=0, verbose_name='Doçent Sayısı'),
        ),
        migrations.AddField(
            model_name='university',
            name='dr_count',
            field=models.IntegerField(default=0, verbose_name='Dr. Öğr. Üyesi Sayısı'),
        ),
        migrations.AddField(
            model_name='university',
            name='education_language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Eğitim Dili'),
        ),
        migrations.AddField(
            model_name='university',
            name='prof_count',
            field=models.IntegerField(default=0, verbose_name='Profesör Sayısı'),
        ),
        migrations.AddField(
            model_name='university',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Tanıtım Videosu (Youtube Embed)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='academician_count',
            field=models.IntegerField(default=0, verbose_name='Toplam Akademisyen Sayısı'),
        ),
    ]
