# Generated by Django 5.2.10 on 2026-01-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_universityanalytics_alter_campusreel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='program_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Program Kodu (YÖK ID)'),
        ),
    ]
