# Generated by Django 5.2.10 on 2026-01-11 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_university_doc_count_university_dr_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campusvenue',
            options={'verbose_name': 'Kampüs Mekanı', 'verbose_name_plural': 'Kampüs Mekanları'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Bölüm / Program', 'verbose_name_plural': 'Bölümler'},
        ),
        migrations.AlterModelOptions(
            name='departmentstats',
            options={'verbose_name': 'Bölüm İstatistiği', 'verbose_name_plural': 'Bölüm İstatistikleri'},
        ),
        migrations.AlterModelOptions(
            name='dormitorydistance',
            options={'verbose_name': 'Yurt-Üniversite Mesafe Kaydı', 'verbose_name_plural': 'Hizmet İlişkileri (Mesafe)'},
        ),
        migrations.AlterModelOptions(
            name='dormitoryimage',
            options={'verbose_name': 'Yurt Galeri Resmi', 'verbose_name_plural': 'Yurt Galerisi'},
        ),
        migrations.AlterModelOptions(
            name='favoritedormitory',
            options={'verbose_name': 'Favori Yurt', 'verbose_name_plural': 'Favori Yurtlar'},
        ),
        migrations.AlterModelOptions(
            name='favoritestudenthouse',
            options={'verbose_name': 'Favori Ev', 'verbose_name_plural': 'Favori Evler'},
        ),
        migrations.AlterModelOptions(
            name='favoriteuniversity',
            options={'verbose_name': 'Favori Üniversite', 'verbose_name_plural': 'Favori Üniversiteler'},
        ),
        migrations.AlterModelOptions(
            name='houseimage',
            options={'verbose_name': 'Ev Resmi', 'verbose_name_plural': 'Ev Galerisi'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Gelen Talep (Lead)', 'verbose_name_plural': 'Gelen Talepler (Leads)'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Haber', 'verbose_name_plural': 'Haberler'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'Burs Fırsatı', 'verbose_name_plural': 'Burs Fırsatları'},
        ),
        migrations.AlterModelOptions(
            name='universityimage',
            options={'verbose_name': 'Üniversite Galeri Resmi', 'verbose_name_plural': 'Üniversite Galerisi'},
        ),
        migrations.AlterModelOptions(
            name='universitystats',
            options={'verbose_name': 'Üniversite İstatistiği', 'verbose_name_plural': 'Üniversite İstatistikleri'},
        ),
        migrations.AddField(
            model_name='studenthouse',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan / Tavsiye (Reklam)'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='discount_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='İndirim Metni'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='distance',
            field=models.CharField(max_length=50, verbose_name='Uzaklık Bilgisi'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='is_sponsored',
            field=models.BooleanField(default=False, verbose_name='Sponsorlu Mekan'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Puan (5 üzerinden)'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='api.university', verbose_name='Bağlı Üniversite'),
        ),
        migrations.AlterField(
            model_name='campusvenue',
            name='venue_type',
            field=models.CharField(max_length=50, verbose_name='Mekan Türü (Cafe, Kırtasiye vb.)'),
        ),
        migrations.AlterField(
            model_name='department',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='departmentstats',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='departmentstats',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='api.department', verbose_name='Bölüm'),
        ),
        migrations.AlterField(
            model_name='departmentstats',
            name='page_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kapasite'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='dorm_covers/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='features',
            field=models.ManyToManyField(blank=True, to='api.feature', verbose_name='Yurt Özellikleri'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Ana Vitrin (Promoted)'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dorm_logos/', verbose_name='Yurt Logosu'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='universities',
            field=models.ManyToManyField(related_name='dormitories', through='api.DormitoryDistance', to='api.university', verbose_name='Hizmet Verilen Üniversiteler'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='dormitory',
            name='website',
            field=models.URLField(blank=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='dormitorydistance',
            name='distance_text',
            field=models.CharField(help_text='Örn: 5 dk Yürüme', max_length=100, verbose_name='Mesafe Bilgisi'),
        ),
        migrations.AlterField(
            model_name='dormitorydistance',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dormitory', verbose_name='Yurt'),
        ),
        migrations.AlterField(
            model_name='dormitorydistance',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Vitrin/Partner Gösterimi'),
        ),
        migrations.AlterField(
            model_name='dormitorydistance',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='dormitoryimage',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.dormitory', verbose_name='Yurt'),
        ),
        migrations.AlterField(
            model_name='dormitoryimage',
            name='image',
            field=models.ImageField(upload_to='dorm_gallery/', verbose_name='Galeri Resmi'),
        ),
        migrations.AlterField(
            model_name='favoritedormitory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='favoritedormitory',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.dormitory', verbose_name='Yurt'),
        ),
        migrations.AlterField(
            model_name='favoritedormitory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_dormitories', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='favoritestudenthouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='favoritestudenthouse',
            name='student_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.studenthouse', verbose_name='Öğrenci Evi'),
        ),
        migrations.AlterField(
            model_name='favoritestudenthouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_houses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='favoriteuniversity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='favoriteuniversity',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='favoriteuniversity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_universities', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, help_text='Örn: Wifi, Coffee', max_length=50, verbose_name='İkon Kodu (Lucide)'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.studenthouse', verbose_name='Öğrenci Evi'),
        ),
        migrations.AlterField(
            model_name='houseimage',
            name='image',
            field=models.ImageField(upload_to='house_gallery/', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu mu?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('SCHOLARSHIP', 'Burs Başvurusu'), ('INFO_REQUEST', 'Bilgi Talebi'), ('CAMPUS_TOUR', 'Kampüs Turu İsteği'), ('DORM_APPLY', 'Yurt Başvurusu')], max_length=20, verbose_name='Talep Türü'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='api.university', verbose_name='İlgili Üniversite'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı (Varsa)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(default='Kampüs Editör', max_length=100, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('Gundem', 'Gündem'), ('Sinav', 'Sınav'), ('Kariyer', 'Kariyer'), ('Yasam', 'Yaşam'), ('Teknoloji', 'Teknoloji'), ('Burslar', 'Burslar')], default='Yasam', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(upload_to='news/covers/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_breaking',
            field=models.BooleanField(default=False, verbose_name='Son Dakika?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Yayında mı?'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL Yolu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Özet (Kısa Açıklama)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Haber Başlığı'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(max_length=100, verbose_name='Burs Miktarı'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='application_url',
            field=models.URLField(blank=True, verbose_name='Başvuru Linki'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(choices=[('Basari', 'Başarı'), ('Ihtiyac', 'İhtiyaç'), ('Spor', 'Spor'), ('Sanat', 'Sanat'), ('Kurumsal', 'Kurumsal'), ('KYK', 'KYK')], default='Basari', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='city',
            field=models.CharField(blank=True, choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50, null=True, verbose_name='Şehir (Varsa)'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(verbose_name='Son Başvuru Tarihi'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='education_level',
            field=models.CharField(choices=[('Lise', 'Lise'), ('Lisans', 'Lisans'), ('YuksekLisans', 'Yüksek Lisans'), ('Doktora', 'Doktora')], default='Lisans', max_length=50, verbose_name='Eğitim Seviyesi'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='scholarships/logos/', verbose_name='Kurum Logosu'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(max_length=200, verbose_name='Burs Veren Kurum'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(verbose_name='Başvuru Şartları'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Burs Adı'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='city',
            field=models.CharField(choices=[('ISTANBUL', 'İstanbul'), ('ANKARA', 'Ankara'), ('IZMIR', 'İzmir'), ('ANTALYA', 'Antalya'), ('ADANA', 'Adana'), ('ADIYAMAN', 'Adıyaman'), ('AFYONKARAHISAR', 'Afyonkarahisar'), ('AGRI', 'Ağrı'), ('AKSARAY', 'Aksaray'), ('AMASYA', 'Amasya'), ('ARDAHAN', 'Ardahan'), ('ARTVIN', 'Artvin'), ('AYDIN', 'Aydın'), ('BALIKESIR', 'Balıkesir'), ('BARTIN', 'Bartın'), ('BATMAN', 'Batman'), ('BAYBURT', 'Bayburt'), ('BILECIK', 'Bilecik'), ('BINGOL', 'Bingöl'), ('BITLIS', 'Bitlis'), ('BOLU', 'Bolu'), ('BURDUR', 'Burdur'), ('BURSA', 'Bursa'), ('CANAKKALE', 'Çanakkale'), ('CANKIRI', 'Çankırı'), ('CORUM', 'Çorum'), ('DENIZLI', 'Denizli'), ('DIYARBAKIR', 'Diyarbakır'), ('DUZCE', 'Düzce'), ('EDIRNE', 'Edirne'), ('ELAZIG', 'Elazığ'), ('ERZINCAN', 'Erzincan'), ('ERZURUM', 'Erzurum'), ('ESKISEHIR', 'Eskişehir'), ('GAZIANTEP', 'Gaziantep'), ('GIRESUN', 'Giresun'), ('GUMUSHANE', 'Gümüşhane'), ('HAKKARI', 'Hakkari'), ('HATAY', 'Hatay'), ('IGDIR', 'Iğdır'), ('ISPARTA', 'Isparta'), ('KAHRAMANMARAS', 'Kahramanmaraş'), ('KARABUK', 'Karabük'), ('KARAMAN', 'Karaman'), ('KARS', 'Kars'), ('KASTAMONU', 'Kastamonu'), ('KAYSERI', 'Kayseri'), ('KIRIKKALE', 'Kırıkkale'), ('KIRKLARELI', 'Kırklareli'), ('KIRSEHIR', 'Kırşehir'), ('KILIS', 'Kilis'), ('KOCAELI', 'Kocaeli'), ('KONYA', 'Konya'), ('KUTAHYA', 'Kütahya'), ('MALATYA', 'Malatya'), ('MANISA', 'Manisa'), ('MARDIN', 'Mardin'), ('MERSIN', 'Mersin'), ('MUGLA', 'Muğla'), ('MUS', 'Muş'), ('NEVSEHIR', 'Nevşehir'), ('NIGDE', 'Niğde'), ('ORDU', 'Ordu'), ('OSMANIYE', 'Osmaniye'), ('RIZE', 'Rize'), ('SAKARYA', 'Sakarya'), ('SAMSUN', 'Samsun'), ('SIIRT', 'Siirt'), ('SINOP', 'Sinop'), ('SIVAS', 'Sivas'), ('SANLIURFA', 'Şanlıurfa'), ('SIRNAK', 'Şırnak'), ('TEKIRDAG', 'Tekirdağ'), ('TOKAT', 'Tokat'), ('TRABZON', 'Trabzon'), ('TUNCELI', 'Tunceli'), ('USAK', 'Uşak'), ('VAN', 'Van'), ('YALOVA', 'Yalova'), ('YOZGAT', 'Yozgat'), ('ZONGULDAK', 'Zonguldak')], max_length=50, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='İletişim Tel'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='house_covers/', verbose_name='Kapak Resmi'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='district',
            field=models.CharField(max_length=100, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='features',
            field=models.ManyToManyField(blank=True, to='api.feature', verbose_name='Ev Özellikleri'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='is_furnished',
            field=models.BooleanField(default=True, verbose_name='Eşyalı mı?'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='price',
            field=models.IntegerField(verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='room_count',
            field=models.CharField(max_length=20, verbose_name='Oda Sayısı'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='square_meters',
            field=models.IntegerField(blank=True, null=True, verbose_name='Metrekare'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='title',
            field=models.CharField(max_length=200, verbose_name='İlan Başlığı'),
        ),
        migrations.AlterField(
            model_name='studenthouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='university',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_university', to=settings.AUTH_USER_MODEL, verbose_name='Yetkili Yönetici'),
        ),
        migrations.AlterField(
            model_name='university',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uni_covers/', verbose_name='Kapak Görseli'),
        ),
        migrations.AlterField(
            model_name='university',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama / Hakkında'),
        ),
        migrations.AlterField(
            model_name='university',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uni_logos/', verbose_name='Üniversite Logosu'),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL Yolu (Slug)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='Toplam Öğrenci Sayısı'),
        ),
        migrations.AlterField(
            model_name='university',
            name='uni_type',
            field=models.CharField(choices=[('DEVLET', 'Devlet'), ('VAKIF', 'Vakıf'), ('OZEL', 'Özel'), ('KIBRIS', 'Kıbrıs'), ('YABANCI', 'Yabancı')], default='DEVLET', max_length=20, verbose_name='Üniversite Türü'),
        ),
        migrations.AlterField(
            model_name='university',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, verbose_name='Web Sitesi'),
        ),
        migrations.AlterField(
            model_name='universityimage',
            name='image',
            field=models.ImageField(upload_to='uni_gallery/', verbose_name='Galeri Resmi'),
        ),
        migrations.AlterField(
            model_name='universityimage',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='page_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Sayfa Görüntülenme'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='phone_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Telefon Tıklama'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='search_appearances',
            field=models.PositiveIntegerField(default=0, verbose_name='Aramada Görünme'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='api.university', verbose_name='Üniversite'),
        ),
        migrations.AlterField(
            model_name='universitystats',
            name='website_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Website Tıklama'),
        ),
    ]
