# Generated by Django 5.2.10 on 2026-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_campusvenue_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkan / Tavsiye (Reklam)'),
        ),
    ]
