# Generated by Django 5.2.10 on 2026-01-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_department_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='program_code',
            field=models.CharField(blank=True, help_text='ÖSYM Program Kodu (Örn: 100110015)', max_length=20, null=True, unique=True, verbose_name='Program Kodu (YÖK ID)'),
        ),
    ]
