# Generated by Django 5.2.10 on 2026-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_department_program_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='school_rank_quota',
        ),
        migrations.AddField(
            model_name='department',
            name='is_english',
            field=models.BooleanField(default=False, verbose_name='İngilizce mi?'),
        ),
        migrations.AddField(
            model_name='department',
            name='scholarship_rate',
            field=models.IntegerField(default=0, verbose_name='Burs Oranı (%)'),
        ),
        migrations.AddField(
            model_name='department',
            name='special_quotas',
            field=models.JSONField(blank=True, default=dict, verbose_name='Özel Kontenjan Detayları'),
        ),
        migrations.AlterField(
            model_name='department',
            name='ranking',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Başarı Sıralaması (Tahmini)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Reklam Görseli'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['score_type', 'ranking'], name='api_departm_score_t_6a2df9_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_english'], name='api_departm_is_engl_501930_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['scholarship_rate'], name='api_departm_scholar_5f411c_idx'),
        ),
    ]
