# Generated by Django 5.2.10 on 2026-01-12 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_university_is_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthouse',
            name='distance_to_uni',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kampüse Uzaklık (Örn: 5 dk yürüme, 2 km)'),
        ),
        migrations.AddField(
            model_name='studenthouse',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_houses', to='api.university', verbose_name='Yakın Olduğu Kampüs/Üniversite'),
        ),
    ]
