# Generated by Django 5.2.10 on 2026-01-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_studenthouse_distance_to_uni_studenthouse_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthouse',
            name='distance_to_uni',
        ),
        migrations.RemoveField(
            model_name='studenthouse',
            name='university',
        ),
        migrations.CreateModel(
            name='StudentHouseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_text', models.CharField(default='Bilinmiyor', max_length=100, verbose_name='Mesafe Bilgisi (Örn: 10 dk yürüme)')),
                ('is_promoted', models.BooleanField(default=False, verbose_name='Vitrin/Partner Gösterimi')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_universities', to='api.studenthouse', verbose_name='Öğrenci Evi')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_houses', to='api.university', verbose_name='Üniversite')),
            ],
            options={
                'verbose_name': 'Üniversiteye Yakın Ev Bağlantısı',
                'verbose_name_plural': 'Üniversiteye Yakın Ev Bağlantıları',
                'unique_together': {('university', 'house')},
            },
        ),
    ]
