# Generated by Django 5.2.10 on 2026-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_department_school_rank_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='academic_staff_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Akademisyen Sayısı (Etiket)'),
        ),
        migrations.AddField(
            model_name='university',
            name='student_count_label',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Öğrenci Sayısı (Etiket)'),
        ),
        migrations.AddField(
            model_name='university',
            name='technopark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Teknopark Adı'),
        ),
        migrations.AlterField(
            model_name='university',
            name='academician_count',
            field=models.IntegerField(default=0, verbose_name='Toplam Akademisyen (Sayısal)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='education_language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Eğitim Dili'),
        ),
        migrations.AlterField(
            model_name='university',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='university',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='Toplam Öğrenci (Sayısal - Sıralama İçin)'),
        ),
    ]
