# Generated by Django 5.2.10 on 2026-01-12 16:42

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_studenthouse_distance_to_uni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık (Örn: %50 Burs İmkanı)')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Alt Başlık')),
                ('description', models.TextField(verbose_name='Kısa Açıklama')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Reklam Görseli')),
                ('button_text', models.CharField(default='Detaylı Bilgi', max_length=50, verbose_name='Buton Yazısı')),
                ('button_link', models.URLField(verbose_name='Yönlenecek Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='api.university')),
            ],
        ),
    ]
