# Generated by Django 5.2 on 2026-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusvenue',
            name='amenities',
            field=models.TextField(blank=True, help_text='Virgülle ayırarak yazınız (Örn: Wifi, Teras, Priz)', verbose_name='İmkanlar'),
        ),
        migrations.AddField(
            model_name='campusvenue',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mekan Açıklaması'),
        ),
        migrations.AddField(
            model_name='campusvenue',
            name='working_hours',
            field=models.TextField(blank=True, help_text='Örn: Hafta İçi: 09:00 - 20:00', verbose_name='Çalışma Saatleri'),
        ),
    ]
